# Generated by Django 4.2 on 2023-05-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_order_ordereddish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
