# Generated by Django 4.2 on 2023-05-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereddish',
            name='dish_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(),
        ),
    ]
