# Generated by Django 4.2 on 2023-05-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_ordereddish_dish_count_alter_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereddish',
            name='dish_now_price',
            field=models.IntegerField(default=50),
        ),
    ]
