# Generated by Django 4.2.1 on 2023-05-30 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_ordereddish_dish_now_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['dish_price'], 'verbose_name': 'блюдо', 'verbose_name_plural': 'блюда'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['order_date', 'pk'], 'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
        migrations.AlterModelOptions(
            name='ordereddish',
            options={'verbose_name': 'блюдо заказа', 'verbose_name_plural': 'блюда заказов'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'cотрудник', 'verbose_name_plural': 'cотрудники'},
        ),
        migrations.AlterField(
            model_name='dish',
            name='dish_compose',
            field=models.TextField(blank=True, null=True, verbose_name='описание блюда'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='dish_name',
            field=models.TextField(blank=True, null=True, verbose_name='название блюда'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='dish_price',
            field=models.IntegerField(verbose_name='цена блюда'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(verbose_name='дата заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.user', verbose_name='имя сотрудника'),
        ),
        migrations.AlterField(
            model_name='ordereddish',
            name='dish_count',
            field=models.IntegerField(default=1, verbose_name='кол-во блюд'),
        ),
        migrations.AlterField(
            model_name='ordereddish',
            name='dish_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.dish', verbose_name='блюдо'),
        ),
        migrations.AlterField(
            model_name='ordereddish',
            name='dish_now_price',
            field=models.IntegerField(default=50, verbose_name='цена блюда на момент заказа'),
        ),
        migrations.AlterField(
            model_name='ordereddish',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.order', verbose_name='заказ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=255, verbose_name='cотрудник'),
        ),
    ]
